import { initializeApp } from 'https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js';
import { getAuth, signInWithEmailAndPassword, onAuthStateChanged, signOut } from 'https://www.gstatic.com/firebasejs/12.18.0/firebase-auth.js';
import { getFirestore, collection, getDocs, doc, setDoc, addDoc, deleteDoc, serverTimestamp } from 'https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js';
import { firebaseConfig } from './firebase-config.js';

const app = initializeApp(firebaseConfig);
const auth = getAuth(app);
const db = getFirestore(app);
const $ = id => document.getElementById(id);
const state = { branches: [], subjects: [], lessons: [], quizzes: [] };
const titles = { dashboard:'الرئيسية', branches:'الفروع', subjects:'المواد', lessons:'الدروس', manual:'اختبار يدوي', import:'استيراد JSON', quizzes:'الاختبارات' };

function setStatus(id, message, good = false) { const el=$(id); if(!el)return; el.textContent=message; el.className=`status ${good?'good':'bad'}`; }
function esc(value) { return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])); }
function makeId(value) { return String(value||'').trim().replace(/\s+/g,'-').replace(/[^\p{L}\p{N}_-]/gu,'').toLowerCase(); }
function branchName(id) { return state.branches.find(x=>x.id===id)?.name||id||'غير معروف'; }
function subjectName(id) { return state.subjects.find(x=>x.id===id)?.name||id||'غير معروف'; }
function lessonName(id) { return state.lessons.find(x=>x.id===id)?.name||id||'غير معروف'; }
function subjectBranches(s) { return Array.isArray(s?.branchIds)?s.branchIds:(s?.branchId?[s.branchId]:[]); }
function lessonBranches(l) { return Array.isArray(l?.branchIds)?l.branchIds:(l?.branchId?[l.branchId]:subjectBranches(state.subjects.find(s=>s.id===l?.subjectId))); }
function firebaseError(e) { const c=e?.code||''; if(c.includes('permission-denied'))return'تم رفض العملية من Firestore Rules. انشر القواعد وتأكد من حساب الأدمن.'; if(c.includes('unauthenticated'))return'جلسة Firebase غير مصادق عليها.'; if(c.includes('invalid-credential')||c.includes('invalid-login-credentials'))return'البريد أو كلمة المرور غير صحيحة.'; return e?.message||'حدث خطأ غير معروف.'; }

async function readCollection(name) { const snap=await getDocs(collection(db,name)); return snap.docs.map(d=>({id:d.id,...d.data()})); }
async function loadData() { const [b,s,l,q]=await Promise.all(['branches','subjects','lessons','quizzes'].map(readCollection)); state.branches=b;state.subjects=s;state.lessons=l;state.quizzes=q; $('cb').textContent=b.length;$('cs').textContent=s.length;$('cl').textContent=l.length;$('cq').textContent=q.length; fillSelects();renderLists();renderQuizzes(); }
function fillSelect(id,items,placeholder,formatter=x=>x.name){const el=$(id);if(!el)return;el.innerHTML='';const first=document.createElement('option');first.value='';first.textContent=placeholder;el.append(first);items.forEach(item=>{const o=document.createElement('option');o.value=item.id;o.textContent=formatter(item);el.append(o)});el.disabled=!items.length;}
function fillSelects(){const b=$('sBranches');b.innerHTML='';state.branches.forEach(x=>{const o=document.createElement('option');o.value=x.id;o.textContent=x.name;b.append(o)});b.disabled=!state.branches.length;fillSelect('lSubject',state.subjects,'اختر المادة',s=>`${s.name} · ${subjectBranches(s).map(branchName).join(' + ')||'بدون فرع'}`);fillSelect('qLesson',state.lessons,'اختر الدرس',l=>`${l.name} · ${subjectName(l.subjectId)}`);}
function showPage(page){document.querySelectorAll('.page').forEach(x=>x.classList.add('hidden'));const p=$(`p-${page}`);if(p)p.classList.remove('hidden');$('title').textContent=titles[page]||'الرئيسية';document.querySelectorAll('[data-page]').forEach(x=>x.classList.toggle('active',x.dataset.page===page));}
document.querySelectorAll('[data-page]').forEach(x=>x.addEventListener('click',()=>showPage(x.dataset.page)));

function renderLists(){
 $('bList').innerHTML=state.branches.length?state.branches.map(b=>`<div class="item"><div><strong>${esc(b.name)}</strong><small>${esc(b.id)}</small></div><button class="btn danger" data-delete="branches" data-id="${esc(b.id)}">حذف</button></div>`).join(''):'<div class="empty">لا توجد فروع.</div>';
 $('sList').innerHTML=state.subjects.length?state.subjects.map(s=>`<div class="item"><div><strong>${esc(s.name)}</strong><small>${esc(subjectBranches(s).map(branchName).join(' · ')||'بدون فرع')} · ${esc(s.id)}</small></div><button class="btn danger" data-delete="subjects" data-id="${esc(s.id)}">حذف</button></div>`).join(''):'<div class="empty">لا توجد مواد.</div>';
 $('lList').innerHTML=state.lessons.length?state.lessons.map(l=>`<div class="item"><div><strong>${esc(l.name)}</strong><small>${esc(subjectName(l.subjectId))} · ${esc(lessonBranches(l).map(branchName).join(' · '))}</small></div><button class="btn danger" data-delete="lessons" data-id="${esc(l.id)}">حذف</button></div>`).join(''):'<div class="empty">لا توجد دروس.</div>';
 document.querySelectorAll('[data-delete]').forEach(btn=>btn.onclick=async()=>{if(!confirm('تأكيد الحذف؟'))return;try{await deleteDoc(doc(db,btn.dataset.delete,btn.dataset.id));await loadData();}catch(e){alert(firebaseError(e));}});
}
$('addB').onclick=async()=>{const name=$('bName').value.trim(),id=makeId($('bId').value||name);if(!name||!id)return setStatus('bMsg','أدخل اسم الفرع.');if(state.branches.some(x=>x.id===id))return setStatus('bMsg','هذا المعرّف موجود مسبقًا.');try{await setDoc(doc(db,'branches',id),{name,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});$('bName').value='';$('bId').value='';await loadData();setStatus('bMsg','تمت إضافة الفرع بنجاح.',true);}catch(e){setStatus('bMsg',firebaseError(e));}};
$('addS').onclick=async()=>{const name=$('sName').value.trim(),id=makeId($('sId').value||name),branchIds=[...$('sBranches').selectedOptions].map(x=>x.value);if(!name||!id||!branchIds.length)return setStatus('sMsg','أدخل اسم المادة واختر فرعًا واحدًا على الأقل.');if(state.subjects.some(x=>x.id===id))return setStatus('sMsg','هذا المعرّف موجود مسبقًا.');try{await setDoc(doc(db,'subjects',id),{name,branchIds,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});$('sName').value='';$('sId').value='';[...$('sBranches').options].forEach(x=>x.selected=false);await loadData();setStatus('sMsg','تمت إضافة المادة وربطها بالفروع.',true);}catch(e){setStatus('sMsg',firebaseError(e));}};
$('addL').onclick=async()=>{const name=$('lName').value.trim(),id=makeId($('lId').value||name),subjectId=$('lSubject').value,s=state.subjects.find(x=>x.id===subjectId);if(!name||!id||!s)return setStatus('lMsg','أدخل اسم الدرس واختر المادة.');if(state.lessons.some(x=>x.id===id))return setStatus('lMsg','هذا المعرّف موجود مسبقًا.');const branchIds=subjectBranches(s);try{await setDoc(doc(db,'lessons',id),{name,subjectId,branchIds,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});$('lName').value='';$('lId').value='';await loadData();setStatus('lMsg','تمت إضافة الدرس وربطه بالمادة وفروعها.',true);}catch(e){setStatus('lMsg',firebaseError(e));}};

let questionNo=0;
function addQuestion(){questionNo++;const n=questionNo,el=document.createElement('article');el.className='question';el.innerHTML=`<div class="qhead"><b>السؤال ${n}</b><button type="button" class="btn danger remove">حذف</button></div><div class="field"><label>نص السؤال</label><textarea class="qt" placeholder="اكتب السؤال"></textarea></div><div class="opts">${[0,1,2,3].map(i=>`<div class="opt"><input class="qo" placeholder="الخيار ${i+1}"><label class="check"><input type="radio" name="correct-${n}" value="${i}"> الإجابة الصحيحة</label></div>`).join('')}</div><div class="field"><label>الشرح (اختياري)</label><input class="qe" placeholder="شرح الإجابة"></div>`;el.querySelector('.remove').onclick=()=>el.remove();$('questions').append(el);}
$('addQ').onclick=addQuestion;
$('saveQ').onclick=async()=>{const lesson=state.lessons.find(x=>x.id===$('qLesson').value),title=$('qTitle').value.trim(),duration=Number($('qDuration').value),questions=[...document.querySelectorAll('.question')].map(el=>{const c=el.querySelector('input[type="radio"]:checked');return{text:el.querySelector('.qt').value.trim(),options:[...el.querySelectorAll('.qo')].map(x=>x.value.trim()),correctIndex:c?Number(c.value):-1,explanation:el.querySelector('.qe').value.trim()};});if(!lesson||!title||!Number.isFinite(duration)||duration<1)return setStatus('qMsg','أكمل الدرس والعنوان والمدة.');if(!questions.length)return setStatus('qMsg','أضف سؤالًا واحدًا على الأقل.');const bad=questions.findIndex(q=>!q.text||q.options.length!==4||q.options.some(x=>!x)||q.correctIndex<0||q.correctIndex>3);if(bad>=0)return setStatus('qMsg',`السؤال ${bad+1} غير مكتمل.`);try{await addDoc(collection(db,'quizzes'),{title,duration,questions,lessonId:lesson.id,subjectId:lesson.subjectId,branchIds:lessonBranches(lesson),createdAt:serverTimestamp(),updatedAt:serverTimestamp(),createdBy:auth.currentUser?.email||''});$('qTitle').value='';$('qDuration').value='10';$('questions').innerHTML='';questionNo=0;await loadData();setStatus('qMsg','تم حفظ الاختبار بنجاح.',true);}catch(e){setStatus('qMsg',firebaseError(e));}};

function parseTests(){const raw=JSON.parse($('json').value),tests=Array.isArray(raw)?raw:raw.tests;if(!Array.isArray(tests)||!tests.length)throw new Error('يجب أن يحتوي JSON على tests ويحتوي اختبارًا واحدًا على الأقل.');tests.forEach((t,i)=>{if(!t?.branch?.id||!t.branch.name||!t?.subject?.id||!t.subject.name||!t?.lesson?.id||!t.lesson.name||!t.title||!Array.isArray(t.questions)||!t.questions.length)throw new Error(`الاختبار ${i+1} ناقص.`);t.questions.forEach((q,j)=>{if(!q?.text||!Array.isArray(q.options)||q.options.length!==4||q.options.some(x=>!String(x).trim())||Number(q.correctIndex)<0||Number(q.correctIndex)>3)throw new Error(`السؤال ${j+1} في الاختبار ${i+1} غير صالح.`);});});return tests;}
$('checkJson').onclick=()=>{try{const t=parseTests();setStatus('jMsg',`JSON صالح · ${t.length} اختبار`,true);}catch(e){setStatus('jMsg',e.message);}};
$('importJson').onclick=async()=>{try{const tests=parseTests();for(const t of tests){const branchIds=Array.isArray(t.subject.branchIds)&&t.subject.branchIds.length?t.subject.branchIds:(Array.isArray(t.branchIds)&&t.branchIds.length?t.branchIds:[t.branch.id]);await setDoc(doc(db,'branches',t.branch.id),{name:t.branch.name,updatedAt:serverTimestamp()},{merge:true});await setDoc(doc(db,'subjects',t.subject.id),{name:t.subject.name,branchIds,updatedAt:serverTimestamp()},{merge:true});await setDoc(doc(db,'lessons',t.lesson.id),{name:t.lesson.name,subjectId:t.subject.id,branchIds,updatedAt:serverTimestamp()},{merge:true});await addDoc(collection(db,'quizzes'),{title:t.title,duration:Number(t.duration)||10,questions:t.questions,lessonId:t.lesson.id,subjectId:t.subject.id,branchIds,createdAt:serverTimestamp(),updatedAt:serverTimestamp(),createdBy:auth.currentUser?.email||''});}await loadData();setStatus('jMsg',`تم استيراد ${tests.length} اختبار إلى Firebase.`,true);}catch(e){setStatus('jMsg',firebaseError(e));}};

function renderQuizzes(){const box=$('quizList');if(!state.quizzes.length){box.innerHTML='<div class="empty">لا توجد اختبارات.</div>';return;}box.innerHTML=state.quizzes.map(q=>`<div class="item"><div><strong>${esc(q.title)}</strong><small>${esc(subjectName(q.subjectId))} · ${esc(lessonName(q.lessonId))} · ${(q.questions?.length||0)} سؤال</small></div><button class="btn danger" data-qdel="${esc(q.id)}">حذف</button></div>`).join('');box.querySelectorAll('[data-qdel]').forEach(btn=>btn.onclick=async()=>{if(!confirm('حذف الاختبار؟'))return;try{await deleteDoc(doc(db,'quizzes',btn.dataset.qdel));await loadData();}catch(e){alert(firebaseError(e));}});}
$('refresh').onclick=async()=>{try{await loadData();}catch(e){alert(firebaseError(e));}};

$('login').addEventListener('submit',async e=>{e.preventDefault();const btn=$('loginBtn');btn.disabled=true;btn.textContent='جارٍ الدخول…';setStatus('authMsg','');try{await signInWithEmailAndPassword(auth,$('email').value.trim(),$('password').value);}catch(err){setStatus('authMsg',firebaseError(err));btn.disabled=false;btn.textContent='تسجيل الدخول';}});
$('logout').onclick=()=>signOut(auth);$('logoutM').onclick=()=>signOut(auth);

onAuthStateChanged(auth,async user=>{if(!user){$('auth').classList.remove('hidden');$('app').classList.add('hidden');return;}$('auth').classList.add('hidden');$('app').classList.remove('hidden');$('who').textContent=`مسجل الدخول: ${user.email}`;showPage('dashboard');try{await loadData();}catch(e){setStatus('bMsg',`تم تسجيل الدخول، لكن تعذر تحميل Firestore: ${firebaseError(e)}`);}$('loginBtn').disabled=false;$('loginBtn').textContent='تسجيل الدخول';});
