import{initializeApp}from'https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js';import{getAuth,signInWithEmailAndPassword,onAuthStateChanged,signOut}from'https://www.gstatic.com/firebasejs/12.18.0/firebase-auth.js';import{getFirestore,collection,getDocs,doc,setDoc,addDoc,deleteDoc,serverTimestamp}from'https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js';import{firebaseConfig}from'./firebase-config.js';
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),$=id=>document.getElementById(id);const S={branches:[],subjects:[],lessons:[],quizzes:[]};let qn=0;
const titles={dashboard:'الرئيسية',branches:'الفروع',subjects:'المواد',lessons:'الدروس',manual:'اختبار يدوي',import:'استيراد JSON',quizzes:'الاختبارات'};
function msg(id,text,ok=false){const e=$(id);if(!e)return;e.textContent=text;e.className='status '+(ok?'good':'bad')}
function err(e){const c=e?.code||'';if(c.includes('permission-denied'))return'تم رفض العملية من Firestore. انشر Rules وتأكد أن هذا الحساب هو الأدمن.';if(c.includes('unauthenticated'))return'جلسة Firebase غير مصادق عليها.';if(c.includes('invalid-credential'))return'البريد أو كلمة المرور غير صحيحة.';return e?.message||'حدث خطأ غير معروف.'}
function idOf(v){return String(v||'').trim().replace(/\s+/g,'-').replace(/[^\w\-\u0600-\u06ff]/g,'').toLowerCase()}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function nameOf(type,id){return S[type].find(x=>x.id===id)?.name||id||'غير معروف'}
async function readAll(){const names=['branches','subjects','lessons','quizzes'];const r=await Promise.all(names.map(n=>getDocs(collection(db,n))));names.forEach((n,i)=>S[n]=r[i].docs.map(d=>({id:d.id,...d.data()})));updateUI()}
function updateUI(){ $('countBranches').textContent=S.branches.length;$('countSubjects').textContent=S.subjects.length;$('countLessons').textContent=S.lessons.length;$('countQuizzes').textContent=S.quizzes.length;fill('subjectBranches',S.branches,'اختر الفروع');fill('lessonSubject',S.subjects,'اختر المادة',x=>x.name);fill('quizLesson',S.lessons,'اختر الدرس',x=>`${x.name} · ${nameOf('subjects',x.subjectId)}`);renderBranches();renderSubjects();renderLessons();renderQuizzes() }
function fill(id,items,placeholder,format=x=>x.name){const s=$(id);if(!s)return;s.innerHTML=`<option value="">${placeholder}</option>`;items.forEach(x=>{const o=document.createElement('option');o.value=x.id;o.textContent=format(x);s.append(o)});s.disabled=!items.length}
function page(p){document.querySelectorAll('.page').forEach(x=>x.classList.add('hidden'));$(`page-${p}`).classList.remove('hidden');$('title').textContent=titles[p];document.querySelectorAll('[data-page]').forEach(x=>x.classList.toggle('active',x.dataset.page===p))}
document.querySelectorAll('[data-page]').forEach(x=>x.onclick=()=>page(x.dataset.page));
function renderBranches(){const b=$('branchList');b.innerHTML=S.branches.length?S.branches.map(x=>`<div class="item"><div><strong>${esc(x.name)}</strong><small>${esc(x.id)}</small></div><button class="btn danger" data-del="branches" data-id="${esc(x.id)}">حذف</button></div>`).join(''):'<div class="empty">لا توجد فروع.</div>';bindDelete(b)}
function renderSubjects(){const b=$('subjectList');b.innerHTML=S.subjects.length?S.subjects.map(x=>`<div class="item"><div><strong>${esc(x.name)}</strong><small>${(x.branchIds||[]).map(id=>esc(nameOf('branches',id))).join(' · ')||'بدون فرع'}</small></div><button class="btn danger" data-del="subjects" data-id="${esc(x.id)}">حذف</button></div>`).join(''):'<div class="empty">لا توجد مواد.</div>';bindDelete(b)}
function renderLessons(){const b=$('lessonList');b.innerHTML=S.lessons.length?S.lessons.map(x=>`<div class="item"><div><strong>${esc(x.name)}</strong><small>${esc(nameOf('subjects',x.subjectId))} · ${(x.branchIds||[]).map(id=>esc(nameOf('branches',id))).join(' · ')}</small></div><button class="btn danger" data-del="lessons" data-id="${esc(x.id)}">حذف</button></div>`).join(''):'<div class="empty">لا توجد دروس.</div>';bindDelete(b)}
function renderQuizzes(){const b=$('quizList');b.innerHTML=S.quizzes.length?S.quizzes.map(x=>`<div class="item"><div><strong>${esc(x.title)}</strong><small>${esc(nameOf('subjects',x.subjectId))} · ${esc(nameOf('lessons',x.lessonId))} · ${(x.questions||[]).length} سؤال</small></div><button class="btn danger" data-del="quizzes" data-id="${esc(x.id)}">حذف</button></div>`).join(''):'<div class="empty">لا توجد اختبارات.</div>';bindDelete(b)}
function bindDelete(box){box.querySelectorAll('[data-del]').forEach(b=>b.onclick=async()=>{if(!confirm('تأكيد الحذف؟'))return;try{await deleteDoc(doc(db,b.dataset.del,b.dataset.id));await readAll()}catch(e){alert(err(e))}})}
$('addBranch').onclick=async()=>{const name=$('branchName').value.trim(),id=idOf($('branchId').value||name);if(!name)return msg('branchStatus','اكتب اسم الفرع.');if(!id)return msg('branchStatus','المعرّف غير صالح.');if(S.branches.some(x=>x.id===id))return msg('branchStatus','هذا الفرع موجود مسبقًا.');try{await setDoc(doc(db,'branches',id),{name,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});$('branchName').value='';$('branchId').value='';await readAll();msg('branchStatus','تمت إضافة الفرع.',true)}catch(e){msg('branchStatus',err(e))}};
$('addSubject').onclick=async()=>{const name=$('subjectName').value.trim(),id=idOf($('subjectId').value||name),branchIds=[...$('subjectBranches').selectedOptions].map(x=>x.value).filter(Boolean);if(!name||!id)return msg('subjectStatus','أدخل اسم المادة.');if(!branchIds.length)return msg('subjectStatus','اختر فرعًا واحدًا على الأقل.');if(S.subjects.some(x=>x.id===id))return msg('subjectStatus','هذا المعرّف مستخدم.');try{await setDoc(doc(db,'subjects',id),{name,branchIds,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});$('subjectName').value='';$('subjectId').value='';await readAll();msg('subjectStatus','تمت إضافة المادة وربطها بالفروع.',true)}catch(e){msg('subjectStatus',err(e))}};
$('addLesson').onclick=async()=>{const name=$('lessonName').value.trim(),id=idOf($('lessonId').value||name),subjectId=$('lessonSubject').value,subject=S.subjects.find(x=>x.id===subjectId);if(!name||!id||!subjectId)return msg('lessonStatus','أدخل اسم الدرس واختر المادة.');if(!subject)return msg('lessonStatus','المادة غير موجودة.');if(S.lessons.some(x=>x.id===id))return msg('lessonStatus','هذا المعرّف مستخدم.');try{await setDoc(doc(db,'lessons',id),{name,subjectId,branchIds:subject.branchIds||[],createdAt:serverTimestamp(),updatedAt:serverTimestamp()});$('lessonName').value='';$('lessonId').value='';await readAll();msg('lessonStatus','تمت إضافة الدرس بنجاح.',true)}catch(e){msg('lessonStatus',err(e))}};
function addQuestion(){qn++;const n=qn,e=document.createElement('article');e.className='question';e.innerHTML=`<div class="qhead"><strong>السؤال ${n}</strong><button type="button" class="btn danger">حذف</button></div><div class="field"><label>نص السؤال</label><textarea class="qt"></textarea></div><div class="opts">${[0,1,2,3].map(i=>`<div class="opt"><input class="qo" placeholder="الخيار ${i+1}"><label class="check"><input type="radio" name="correct-${n}" value="${i}"> صحيح</label></div>`).join('')}</div><div class="field"><label>الشرح اختياري</label><input class="qe"></div>`;e.querySelector('.btn').onclick=()=>e.remove();$('questions').append(e)}$('addQuestion').onclick=addQuestion;
$('saveQuiz').onclick=async()=>{const lesson=S.lessons.find(x=>x.id===$('quizLesson').value),title=$('quizTitle').value.trim(),duration=Number($('quizDuration').value),questions=[...document.querySelectorAll('.question')].map(e=>{const r=e.querySelector('input[type=radio]:checked');return{text:e.querySelector('.qt').value.trim(),options:[...e.querySelectorAll('.qo')].map(x=>x.value.trim()),correctIndex:r?Number(r.value):-1,explanation:e.querySelector('.qe').value.trim()}});if(!lesson||!title||!Number.isFinite(duration)||duration<1)return msg('quizStatus','أكمل الدرس والعنوان والمدة.');if(!questions.length)return msg('quizStatus','أضف سؤالًا واحدًا على الأقل.');const bad=questions.findIndex(q=>!q.text||q.options.length!==4||q.options.some(x=>!x)||q.correctIndex<0);if(bad>=0)return msg('quizStatus',`السؤال ${bad+1} غير مكتمل.`);try{await addDoc(collection(db,'quizzes'),{title,duration,questions,lessonId:lesson.id,subjectId:lesson.subjectId,branchIds:lesson.branchIds||[],createdAt:serverTimestamp(),updatedAt:serverTimestamp(),createdBy:auth.currentUser.email});$('quizTitle').value='';$('questions').innerHTML='';qn=0;await readAll();msg('quizStatus','تم حفظ الاختبار.',true)}catch(e){msg('quizStatus',err(e))}};
function parseTests(){const x=JSON.parse($('jsonInput').value);const tests=Array.isArray(x)?x:x.tests;if(!Array.isArray(tests)||!tests.length)throw Error('يجب أن يحتوي JSON على tests[] أو يكون مصفوفة اختبارات.');return tests}
function validateTest(t){if(!t?.branch?.id||!t?.subject?.id||!t?.lesson?.id||!t.title||!Array.isArray(t.questions)||!t.questions.length)throw Error('بيانات اختبار ناقصة.');if(t.questions.some(q=>!q.text||!Array.isArray(q.options)||q.options.length!==4||q.options.some(x=>!String(x).trim())||Number(q.correctIndex)<0||Number(q.correctIndex)>3))throw Error(`اختبار "${t.title}" يحتوي سؤالًا غير صالح.`)}
$('validateJson').onclick=()=>{try{const t=parseTests();t.forEach(validateTest);msg('jsonStatus',`JSON صالح: ${t.length} اختبار.`,true)}catch(e){msg('jsonStatus',e.message)}};
$('importJson').onclick=async()=>{try{const tests=parseTests();tests.forEach(validateTest);for(const t of tests){const branchIds=t.subject.branchIds||t.branchIds||[t.branch.id];await setDoc(doc(db,'branches',t.branch.id),{name:t.branch.name,updatedAt:serverTimestamp()},{merge:true});await setDoc(doc(db,'subjects',t.subject.id),{name:t.subject.name,branchIds,updatedAt:serverTimestamp()},{merge:true});const lessonBranches=t.lesson.branchIds||branchIds;await setDoc(doc(db,'lessons',t.lesson.id),{name:t.lesson.name,subjectId:t.subject.id,branchIds:lessonBranches,updatedAt:serverTimestamp()},{merge:true});await addDoc(collection(db,'quizzes'),{title:t.title,duration:Number(t.duration)||10,questions:t.questions,lessonId:t.lesson.id,subjectId:t.subject.id,branchIds:lessonBranches,createdAt:serverTimestamp(),updatedAt:serverTimestamp(),createdBy:auth.currentUser.email})}await readAll();msg('jsonStatus',`تم استيراد ${tests.length} اختبار.`,true)}catch(e){msg('jsonStatus',err(e))}};
$('refresh').onclick=async()=>{try{await readAll()}catch(e){alert(err(e))}};
$('login').onsubmit=async e=>{e.preventDefault();const btn=$('loginBtn');btn.disabled=true;msg('authMsg','جارٍ تسجيل الدخول...',true);try{await signInWithEmailAndPassword(auth,$('email').value.trim(),$('password').value);msg('authMsg','تم تسجيل الدخول.',true)}catch(e){msg('authMsg',err(e))}finally{btn.disabled=false}};
$('logout').onclick=$('logoutMobile').onclick=()=>signOut(auth);
onAuthStateChanged(auth,async user=>{if(!user){$('auth').classList.remove('hidden');$('app').classList.add('hidden');$('who').textContent='';return}$('auth').classList.add('hidden');$('app').classList.remove('hidden');$('who').textContent=user.email;page('dashboard');try{await readAll()}catch(e){msg('branchStatus','تم الدخول بنجاح، لكن تعذر تحميل Firestore: '+err(e))}});